name = "jsonderulo-pipeline-ui"
compatibility_date = "2024-01-15"

[env.production]
name = "jsonderulo-pipeline-ui"

[env.production.vars]
NODE_ENV = "production"

# Cloudflare Pages configuration
[[env.production.services]]
service = "jsonderulo-api"
environment = "production"

# Build configuration
[build]
command = "npm run build:ui"
cwd = "."
watch_dir = "ui/src"

[build.upload]
format = "directory"
dir = "dist-ui"